*  AUTHOR           : ROMANI EZZAT     r.ezzat@masaref-bsc.com
*  DATE             : 18 OCT 2021
*  CLIENT           : BDC
*  MODULE			: CUSTOMER
*  DESCRIPTION      : ROUTINE TO CHECK THE CORP SIZE
*  ATTACHED TO		: CUSTOMER,MBSC.CORP.INPUT
*-----------------------------------------------------------------------------
    SUBROUTINE V.MBSC.CORP.SIZE.VAL
*-----------------------------------------------------------------------------
    $INSERT I_COMMON
    $INSERT I_EQUATE
	$INSERT I_F.CUSTOMER
    $INSERT I_F.MBSC.SME.CAT.PARAM
	$INSERT I_F.MBSC.CUS.ACTIVITYTYPE
*-----------------------------------------------------------------------------
	*DEBUG
*-----------------------------------------------------------------------------
	
	FN.MBSC.SME.CAT.PARAM = 'F.MBSC.SME.CAT.PARAM'
	F.MBSC.SME.CAT.PARAM = ''
	CALL OPF(FN.MBSC.SME.CAT.PARAM,F.MBSC.SME.CAT.PARAM)

	FN.MBSC.CUS.ACTIVITYTYPE = 'F.MBSC.CUS.ACTIVITYTYPE'
	F.MBSC.CUS.ACTIVITYTYPE = ''
	CALL OPF(FN.MBSC.CUS.ACTIVITYTYPE,F.MBSC.CUS.ACTIVITYTYPE)
	
	CORP.SIZE.ID = ''
	START.DATE  = ''
	T.DATE = TODAY
	SME.TYPE = ''
	INDUST.TYPE = ''
	ACTIV.TYPE = '0'
	TURN.OVER = '0'
	P.CAPITAL = '0'

	CALL GET.LOC.REF("CUSTOMER","ACTIVITYTYPE",ACTTYPE.POS)
	ACTIV.TYPE = R.NEW(EB.CUS.LOCAL.REF)<1,ACTTYPE.POS>
	
	* READ FROM ACTIVITY TYPE TABLE TO GET INDUSTRIAL TYPE
	CALL F.READ(FN.MBSC.CUS.ACTIVITYTYPE,ACTIV.TYPE,R.ACTIVITY,F.MBSC.CUS.ACTIVITYTYPE,ERR.ACTIVITYTYPE)
	INDUST.TYPE = R.ACTIVITY<ACTIVITY.TYPE.ACT.TYPE>
	
	CALL GET.LOC.REF("CUSTOMER","PAIDCAPITAL",CAP.POS)
	P.CAPITAL = R.NEW(EB.CUS.LOCAL.REF)<1,CAP.POS>
	
	CALL GET.LOC.REF("CUSTOMER","L.TURNOVER",TURN.POS)
	TURN.OVER = R.NEW(EB.CUS.LOCAL.REF)<1,TURN.POS>
	
	CALL GET.LOC.REF("CUSTOMER","L.BUS.STAR.DATE",STARTDATE.POS)
	START.DATE = R.NEW(EB.CUS.LOCAL.REF)<1,STARTDATE.POS>

	IF START.DATE NE '' THEN
		FREQ = 'M12'
		D.DDY = START.DATE[7,2]
		
		OLD.COMI = COMI

		COMI = START.DATE:FREQ:D.DDY
		CALL CFQ
		NEXT.YEAR = COMI[1,8]
		COMI = OLD.COMI
	END
	
	IF NEXT.YEAR GE T.DATE THEN 
		SME.TYPE.1 = 'NEW' 
	END
	
	IF NEXT.YEAR LT T.DATE THEN 
		SME.TYPE.1 = 'OLD'
	END
	
	CALL GET.LOC.REF('CUSTOMER','CORP.SIZE',SIZE.POS)

	IF SME.TYPE.1 EQ 'OLD' THEN
		T.SEL = ''  ;  KEY.LIST = ''  ; SELECTED = ''
		T.SEL = "SELECT ":F.MBSC.SME.CAT.PARAM:" WITH SME.TYPE EQ ":SME.TYPE.1:" AND MIN.TURN.OVER LE ":TURN.OVER: " AND MAX.TURN.OVER GT ":TURN.OVER
		CALL EB.READLIST(T.SEL,KEY.LIST,"",SELECTED,SEL.ERR)

		CORP.SIZE.ID = KEY.LIST<1> 

		IF CORP.SIZE.ID EQ '' THEN
			T.SEL = ''  ;  KEY.LIST = ''  ; SELECTED = ''
			T.SEL = "SELECT ":F.MBSC.SME.CAT.PARAM:" WITH SME.TYPE EQ ":SME.TYPE.1:" AND MIN.TURN.OVER LE ":TURN.OVER: " AND MAX.TURN.OVER EQ 0"
			CALL EB.READLIST(T.SEL,KEY.LIST,"",SELECTED,SEL.ERR)
			CORP.SIZE.ID = KEY.LIST<1> 
		END 

		*=============================================================
		R.NEW(EB.CUS.LOCAL.REF)<1,SIZE.POS> = CORP.SIZE.ID
		*==============================================================
    END
	

	IF  SME.TYPE.1 EQ 'NEW' THEN
		T.SEL = ''  ;  KEY.LIST = ''  ; SELECTED = ''
		T.SEL = 'SELECT F.MBSC.SME.CAT.PARAM WITH SME.TYPE EQ NEW AND ACT.TYPE EQ ':INDUST.TYPE:' AND MIN.PAID.CAPTIAL LE ':P.CAPITAL:' AND MAX.PAID.CAPTIAL GT ':P.CAPITAL
		CALL EB.READLIST(T.SEL,KEY.LIST,"",SELECTED,SEL.ERR)

		CORP.SIZE.ID = KEY.LIST<1> 

		IF CORP.SIZE.ID EQ '' THEN
			T.SEL = ''  ;  KEY.LIST = ''  ; SELECTED = ''
			T.SEL = 'SELECT F.MBSC.SME.CAT.PARAM WITH SME.TYPE EQ NEW AND ACT.TYPE EQ ':INDUST.TYPE:' AND MIN.PAID.CAPTIAL LE ':P.CAPITAL:' AND MAX.PAID.CAPTIAL EQ 0'
			CALL EB.READLIST(T.SEL,KEY.LIST,"",SELECTED,SEL.ERR)
			CORP.SIZE.ID = KEY.LIST<1> 
		END

		*=============================================================
		R.NEW(EB.CUS.LOCAL.REF)<1,SIZE.POS> = CORP.SIZE.ID
		*==============================================================
	END

	IF SME.TYPE.1 EQ '' THEN
		R.NEW(EB.CUS.LOCAL.REF)<1,SIZE.POS> = ''	
  	END
*-----------------------------------------------------------------------------
RETURN
END
